import Head from "next/head";
import Image from "next/image";
import {
  Button,
  CardTitle,
  Circle,
  Container,
  Footer,
  Main,
  Menu,
  Title,
} from "../../styles/pages/home";
import menu from "../assets/menu.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Menu>
          <Image alt="" src={menu} width={50} height={50} />
        </Menu>
        <Container>
          <CardTitle>
            <Title>MICHAEL CHIERICI</Title>
            <Button>Resumo</Button>
          </CardTitle>
          <Circle />
        </Container>
      </Main>
      <Footer />
    </>
  );
}
