import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col  ml-6 h-screen">
        <nav className="bg-green500 flex justify-end items-center h-11 mr-6">
          <h1>Menu</h1>
        </nav>
        <div className="bg-gray500 flex flex-row items-center rounded w-10/12  h-3/5 relative">
          <div className="bg-blue500 flex justify-center rounded w-2/4 h-2/5 z-10 relative mb-auto">
            MICHAEL CHIERICI,{"\n"}
            DESENVOLVEDOR{"\n"}
            FRONT-END
            <div>
              <button className="bg-green500 rounded mt-12">Resumo</button>
            </div>
          </div>

          <div className="bg-black600 flex items-center justify-center w-1/4 h-4/6 z-0 rounded-full">
            <h1 className="bg-green500 rounded">Image</h1>
          </div>
        </div>

        <footer className="bg-blue500 w-10/12 rounded mt-auto mb-7">
          Icons
        </footer>
      </div>
    </>
  );
}
